---
title: "Aufgabe_4"
author: "windijon"
date: '2022-05-16'
output: html_document
---


### Task 1: Write your own functions

Load the necessary libraries.

```{r message = FALSE}

library(readr)        # to import tabular data (e.g. csv)
library(dplyr)        # to manipulate (tabular) data
library(ggplot2)      # to visualize data
library(sf)           # to handle spatial vector data
library(terra)        # To handle raster data
library(lubridate)    # To handle dates and times
library(zoo)          # to handle Rolling window functions
library(scales)       # to handle thousands separator

```

Create a function for our Euclidean distance calculation.

```{r message = FALSE}

Euclidean_Distance <- function(E_Cord1, E_Cord2, N_Cord1, N_Cord2){
  sqrt((E_Cord1 - E_Cord2)^2 + (N_Cord1 - N_Cord2)^2)
}

Euclidean_Distance(E_Cord1 = 2570589, E_Cord2 = 2570573, N_Cord1 = 1205095, N_Cord2 = 1205096)

```


### Task 2: Prepare Analysis

Import the wild-boar data "wildschwein_BE_2056" as csv.

```{r message = FALSE}

wildschwein <- read_delim("wildschwein_BE_2056.csv",",")
wildschwein

```

Filter the individuals Rosa and Sabi for the time-span 01.04.2015 - 15.04.2015

```{r}

filter_wildschwein <- wildschwein %>% 
  filter(TierName == c("Sabi", "Rosa"), DatetimeUTC >= as.Date("2015-04-01"), DatetimeUTC <= as.Date("2015-04-15"))
filter_wildschwein

```


### Task 3: Create Join Key

Round the minutes of "DatetimeUTC" to a multiple of 15 minutes, to match the two animals temporally.

```{r}

filter_wildschwein <- filter_wildschwein %>% 
  mutate(DatetimeRound = round_date(DatetimeUTC, unit = "15 minutes"))
filter_wildschwein

```

